"""rework schema for knowledge_type organizations threads chat

Revision ID: 13acffaf49db
Revises: d6c40b2a9a59
Create Date: 2026-09-10 14:57:27.896005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13acffaf49db"
down_revision: Union[str, Sequence[str], None] = "d6c40b2a9a59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunking_strategies",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_platform_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "uq_chunking_strategies_default",
        "chunking_strategies",
        ["is_platform_default"],
        unique=True,
        postgresql_where=sa.text("is_platform_default"),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "knowledge_access",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_type", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "knowledge_type",
            name="uq_knowledge_access_org_user_type",
        ),
    )
    op.create_index(
        op.f("ix_knowledge_access_organization_id"),
        "knowledge_access",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_access_user_id"),
        "knowledge_access",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "organization_members",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_organization_members_user"),
    )
    op.create_index(
        op.f("ix_organization_members_organization_id"),
        "organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_members_user_id"),
        "organization_members",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "threads",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_threads_user_id"), "threads", ["user_id"], unique=False)
    op.create_table(
        "chat_history",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_history_thread_id"), "chat_history", ["thread_id"], unique=False
    )
    op.add_column("document_chunks", sa.Column("user_id", sa.UUID(), nullable=False))
    op.add_column(
        "document_chunks", sa.Column("organization_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "document_chunks",
        sa.Column("knowledge_type", sa.String(length=16), nullable=False),
    )
    op.drop_index(
        op.f("ix_document_chunks_knowledge_base_id"), table_name="document_chunks"
    )
    op.drop_constraint(
        op.f("document_chunks_knowledge_base_id_fkey"),
        "document_chunks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "document_chunks",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "document_chunks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("document_chunks", "knowledge_base_id")
    op.add_column("documents", sa.Column("organization_id", sa.UUID(), nullable=True))
    op.add_column(
        "documents", sa.Column("document_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "documents", sa.Column("document_type", sa.String(length=16), nullable=False)
    )
    op.add_column(
        "documents", sa.Column("knowledge_type", sa.String(length=16), nullable=False)
    )
    op.add_column(
        "documents", sa.Column("knowledge_base", sa.String(length=16), nullable=False)
    )
    op.add_column(
        "documents", sa.Column("chunk_strategy_id", sa.UUID(), nullable=False)
    )
    op.add_column(
        "documents", sa.Column("embedding_model_id", sa.UUID(), nullable=False)
    )
    op.add_column("documents", sa.Column("chunks_count", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_documents_knowledge_base_id"), table_name="documents")
    op.create_index(
        op.f("ix_documents_organization_id"),
        "documents",
        ["organization_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_documents_organization_content_hash",
        "documents",
        ["organization_id", "content_hash"],
    )
    op.drop_constraint(
        op.f("documents_knowledge_base_id_fkey"), "documents", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "documents", "chunking_strategies", ["chunk_strategy_id"], ["id"]
    )
    op.create_foreign_key(
        None, "documents", "provider_models", ["embedding_model_id"], ["id"]
    )
    op.create_foreign_key(
        None,
        "documents",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("documents", "knowledge_base_id")
    op.drop_column("documents", "chunk_count")
    op.drop_column("documents", "filename")
    op.drop_column("documents", "chunking_strategy")
    op.drop_index(op.f("ix_knowledge_bases_user_id"), table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    op.add_column("users", sa.Column("model_id", sa.UUID(), nullable=True))
    op.add_column("users", sa.Column("embedding_model_id", sa.UUID(), nullable=True))
    op.add_column("users", sa.Column("chunk_splitter_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "users", "chunking_strategies", ["chunk_splitter_id"], ["id"]
    )
    op.create_foreign_key(
        None, "users", "provider_models", ["embedding_model_id"], ["id"]
    )
    op.create_foreign_key(None, "users", "provider_models", ["model_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_bases",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "embedding_provider",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "embedding_model",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "embedding_dimensions", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "vector_store_provider",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "vector_store_ref",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_locked", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("knowledge_bases_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("knowledge_bases_pkey")),
    )
    op.create_index(
        op.f("ix_knowledge_bases_user_id"), "knowledge_bases", ["user_id"], unique=False
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "chunk_splitter_id")
    op.drop_column("users", "embedding_model_id")
    op.drop_column("users", "model_id")
    op.add_column(
        "documents",
        sa.Column(
            "chunking_strategy",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "documents",
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "documents",
        sa.Column("chunk_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "documents",
        sa.Column("knowledge_base_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("documents_knowledge_base_id_fkey"),
        "documents",
        "knowledge_bases",
        ["knowledge_base_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "uq_documents_organization_content_hash", "documents", type_="unique"
    )
    op.drop_index(op.f("ix_documents_organization_id"), table_name="documents")
    op.create_index(
        op.f("ix_documents_knowledge_base_id"),
        "documents",
        ["knowledge_base_id"],
        unique=False,
    )
    op.drop_column("documents", "chunks_count")
    op.drop_column("documents", "embedding_model_id")
    op.drop_column("documents", "chunk_strategy_id")
    op.drop_column("documents", "knowledge_base")
    op.drop_column("documents", "knowledge_type")
    op.drop_column("documents", "document_type")
    op.drop_column("documents", "document_name")
    op.drop_column("documents", "organization_id")
    op.add_column(
        "document_chunks",
        sa.Column("knowledge_base_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "document_chunks", type_="foreignkey")
    op.drop_constraint(None, "document_chunks", type_="foreignkey")
    op.create_foreign_key(
        op.f("document_chunks_knowledge_base_id_fkey"),
        "document_chunks",
        "knowledge_bases",
        ["knowledge_base_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_document_chunks_knowledge_base_id"),
        "document_chunks",
        ["knowledge_base_id"],
        unique=False,
    )
    op.drop_column("document_chunks", "knowledge_type")
    op.drop_column("document_chunks", "organization_id")
    op.drop_column("document_chunks", "user_id")
    op.drop_index(op.f("ix_chat_history_thread_id"), table_name="chat_history")
    op.drop_table("chat_history")
    op.drop_index(op.f("ix_threads_user_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(
        op.f("ix_organization_members_user_id"), table_name="organization_members"
    )
    op.drop_index(
        op.f("ix_organization_members_organization_id"),
        table_name="organization_members",
    )
    op.drop_table("organization_members")
    op.drop_index(op.f("ix_knowledge_access_user_id"), table_name="knowledge_access")
    op.drop_index(
        op.f("ix_knowledge_access_organization_id"), table_name="knowledge_access"
    )
    op.drop_table("knowledge_access")
    op.drop_table("organizations")
    op.drop_index(
        "uq_chunking_strategies_default",
        table_name="chunking_strategies",
        postgresql_where=sa.text("is_platform_default"),
    )
    op.drop_table("chunking_strategies")
    # ### end Alembic commands ###
